# Generated by Django 5.2.14 on 2026-05-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidadao',
            options={'verbose_name': 'cidadao', 'verbose_name_plural': 'cidadaos'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'endereco', 'verbose_name_plural': 'enderecos'},
        ),
    ]
