# Generated by Django 5.2.14 on 2026-05-30 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cidadao_options_alter_endereco_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='naturalidade',
            field=models.CharField(default='Nao informado', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidadao',
            name='rg_data_expedicao',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidadao',
            name='rg_numero',
            field=models.CharField(default='RG_IMPORTADO', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
