# Generated by Django 5.2.14 on 2026-05-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cidadao_naturalidade_cidadao_rg_data_expedicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
