# Generated by Django 5.2.14 on 2026-05-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cidadao_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='rg_orgao_emissor',
            field=models.CharField(default='ITEP/RN', max_length=50),
            preserve_default=False,
        ),
    ]
