# Generated by Django 5.2.14 on 2026-06-01 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cidadao_rg_orgao_emissor'),
        ('ubs', '0006_fix_enderecoubs_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='ubs.ubs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubs_admin_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin de ubs',
                'verbose_name_plural': 'admins de ubs',
                'constraints': [models.UniqueConstraint(fields=('user', 'ubs'), name='unique_user_ubs_admin')],
            },
        ),
    ]
