# Generated by Django 5.2.14 on 2026-05-30 04:12

import apps.agendamentos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_cidadao_whatsapp'),
        ('ubs', '0002_especialidade_ubs_especialidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorrente', models.BooleanField(default=False)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], null=True)),
                ('data_vaga', models.DateField(blank=True, null=True)),
                ('data_inicio_recorrencia', models.DateField(blank=True, null=True)),
                ('data_fim_recorrencia', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('cadastro_abre_em', models.DateTimeField()),
                ('cadastro_fecha_em', models.DateTimeField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('protocolo', models.CharField(default=apps.agendamentos.models.gerar_protocolo, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('EXECUTADO', 'Executado'), ('CANCELADO_PACIENTE', 'Cancelado pelo paciente'), ('CANCELADO_UBS', 'Cancelado pela UBS'), ('FALTA', 'Falta')], default='CONFIRMADO', max_length=20)),
                ('cidadao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='core.cidadao')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas_agendamento', to='ubs.especialidade')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_agendamento', to='ubs.ubs')),
            ],
            options={
                'verbose_name': 'vaga de agendamento',
                'verbose_name_plural': 'vagas de agendamento',
                'ordering': ['data_vaga', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('data_vaga__isnull', False)), fields=('ubs', 'especialidade', 'data_vaga', 'hora_inicio'), name='uniq_vaga_especifica_por_ubs_especialidade_horario')],
            },
        ),
    ]
