# Generated by Django 5.2.14 on 2026-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagaagendamento',
            name='chamado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vagaagendamento',
            name='senha_atendimento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vagaagendamento',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('EXECUTADO', 'Executado'), ('CANCELADO_PACIENTE', 'Cancelado pelo paciente'), ('CANCELADO_UBS', 'Cancelado pela UBS'), ('FALTA', 'Falta'), ('CHAMADO', 'Chamado')], default='CONFIRMADO', max_length=20),
        ),
    ]
