# Generated by Django 5.2.14 on 2026-05-30 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(max_length=20, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('distrito_sanitario', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('permite_agendamento_online', models.BooleanField(default=False)),
                ('antecedencia_maxima_dias', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ubs',
                'verbose_name_plural': 'ubs',
            },
        ),
        migrations.CreateModel(
            name='EnderecoUbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('ubs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='ubs.ubs')),
            ],
            options={
                'verbose_name': 'endereco da ubs',
                'verbose_name_plural': 'enderecos das ubs',
            },
        ),
    ]
