# Generated by Django 5.2.14 on 2026-05-30 04:00

from pathlib import Path
import re

from django.db import migrations, models


def load_especialidades(apps, schema_editor):
    Especialidade = apps.get_model("ubs", "Especialidade")
    arquivo = Path(schema_editor.connection.settings_dict["NAME"]).resolve().parent / "especialidades_medicas.txt"

    if not arquivo.exists():
        arquivo = Path(__file__).resolve().parents[3] / "especialidades_medicas.txt"

    padrao = re.compile(r"^([0-9A-Z]{6})\t(.+)$")
    vistos = set()

    for linha in arquivo.read_text(encoding="utf-8").splitlines():
        correspondencia = padrao.match(linha.strip())
        if not correspondencia:
            continue

        codigo, nome = correspondencia.groups()
        if codigo in vistos:
            continue

        vistos.add(codigo)
        Especialidade.objects.create(cbo_codigo=codigo, nome=nome)


def unload_especialidades(apps, schema_editor):
    Especialidade = apps.get_model("ubs", "Especialidade")
    Especialidade.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cbo_codigo", models.CharField(max_length=6, unique=True)),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "especialidade",
                "verbose_name_plural": "especialidades",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="ubs",
            name="especialidades",
            field=models.ManyToManyField(blank=True, related_name="ubs", to="ubs.especialidade"),
        ),
        migrations.RunPython(load_especialidades, unload_especialidades),
    ]