# Generated by Django 5.2.14 on 2026-06-01 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('AUTH', 'Autenticação'), ('AGEND', 'Agendamento'), ('UBS', 'UBS'), ('CID', 'Cidadão'), ('ERRO', 'Erro'), ('SIS', 'Sistema')], db_index=True, default='SIS', max_length=5)),
                ('acao', models.CharField(max_length=200)),
                ('usuario_str', models.CharField(blank=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('eh_erro', models.BooleanField(db_index=True, default=False)),
                ('traceback', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
